language: go

sudo: required

services:
  - docker

go:
  - "1.11.x"

env:
  - GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls

install:
  - go mod vendor

before_script:
  - docker run -d -p 127.0.0.1:1883:1883 thethingsnetwork/rabbitmq

script:
  - go build
  - go test -v -cover 

after_script:
  - goveralls -service=travis-ci
