language: go

sudo: required

services:
  - docker

go:
  - 1.9.7

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure

before_script:
  - echo $TRAVIS_GO_VERSION
  - docker run -d -p 127.0.0.1:1883:1883 thethingsnetwork/rabbitmq

script:
  - go test -v -cover .

after_script:
  - goveralls -service=travis-ci
