language: go

sudo: required

services:
  - docker

go:
  - 1.11.4
  - 1.11.3
  - 1.11.2
  - 1.11.1
  - 1.11

env:
  - GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls

install:
  # - go mod vendor

before_script:
  - docker run -d -p 127.0.0.1:1883:1883 thethingsnetwork/rabbitmq

script:
  - go clean -cache
  - go build
  - go test -v -cover 

after_script:
  - goveralls -service=travis-ci
