language: go

sudo: required

services:
  - docker

go:
  - 1.9

before_install:
  - go get github.com/kardianos/govendor
  - go get github.com/mattn/goveralls

install:
  - govendor sync -v

before_script:
  - docker run -d -p 127.0.0.1:1883:1883 thethingsnetwork/rabbitmq

script:
  - go test -v -cover .

after_script:
  - goveralls -service=travis-ci
